// Database of Trusted and Popular Extensions (Reputation-Based Whitelist)
// The ID is cryptographically secure and generated by the Chrome Web Store, making it spoof-proof.

const TRUSTED_EXTENSIONS = {
  "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
    "name": "uBlock Origin",
    "category": "Utility / Ad-blocker",
    "description": "An efficient blocker wide-range content filtering tool."
  },
  "gighmmpiobklfepjocnamgkkbiglidom": {
    "name": "AdBlock",
    "category": "Utility / Ad-blocker",
    "description": "Block YouTube ads, pop-ups and fight malware."
  },
  "cfhdojbhahnkbcjphkbamkdaibjbiifa": {
    "name": "Adblock Plus",
    "category": "Utility / Ad-blocker",
    "description": "Block annoying ads and pop-ups on YouTube, Facebook, and other sites."
  },
  "nkbihfbeogaeaoehlefnkodbdfgpgknn": {
    "name": "MetaMask",
    "category": "Finance / Crypto Wallet",
    "description": "Ethereum wallet and dApp gateway inside your browser."
  },
  "kbfnbcaeplbcioaajpdfaonanjoecbfb": {
    "name": "Grammarly",
    "category": "Productivity / Writing Assistant",
    "description": "Spelling and grammar checking tool."
  },
  "aapbdbdojonhghflgkfoihobokbiecmc": {
    "name": "Google Translate",
    "category": "Utility / Translation",
    "description": "View translations easily as you browse the web."
  },
  "aeblmdajoegokailbcgabcjoihdepeih": {
    "name": "1Password",
    "category": "Security / Password Manager",
    "description": "Password manager helper to autofill and generate strong credentials."
  },
  "hdokiejnpimbiinobcebhfibihjonbee": {
    "name": "LastPass",
    "category": "Security / Password Manager",
    "description": "Access and autofill your passwords from any browser."
  },
  "efaidnbmnnnibpcajpcglclefindmkaj": {
    "name": "Adobe Acrobat",
    "category": "Productivity / PDF Viewer",
    "description": "Convert, edit, sign, and view PDF files directly in your tab."
  },
  "nmmhkkegccagldgiimedgfjegggjhdcd": {
    "name": "Google Chrome Web Store Payments",
    "category": "System / Payment",
    "description": "Built-in Google Chrome extension for processing web store payments."
  }
};

// Export for background.js compatibility (in case ES modules are used)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TRUSTED_EXTENSIONS;
}
